# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
#import inst_rc
class Ui_MusicalInstruments(object):
    def setupUi(self, MusicalInstruments):
        MusicalInstruments.setObjectName("MusicalInstruments")
        MusicalInstruments.resize(807, 702)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(192)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(MusicalInstruments.sizePolicy().hasHeightForWidth())
        MusicalInstruments.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../task1-team__12/project/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MusicalInstruments.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MusicalInstruments)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 783, 678))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("guit.jpeg"))
        self.label_11.setScaledContents(True)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.g1 = QtWidgets.QPushButton(self.widget)
        self.g1.setStyleSheet("background-color:rgb(0, 0, 0)\n"
"")
        self.g1.setText("")
        self.g1.setObjectName("g1")
        self.verticalLayout_4.addWidget(self.g1)
        self.g2 = QtWidgets.QPushButton(self.widget)
        self.g2.setStyleSheet("\n"
"background-color:rgb(0,0,0)\n"
"\n"
"\n"
"")
        self.g2.setText("")
        self.g2.setObjectName("g2")
        self.verticalLayout_4.addWidget(self.g2)
        self.g3 = QtWidgets.QPushButton(self.widget)
        self.g3.setStyleSheet("background-color:rgb(0,0,0)\n"
"\n"
"")
        self.g3.setText("")
        self.g3.setObjectName("g3")
        self.verticalLayout_4.addWidget(self.g3)
        self.g4 = QtWidgets.QPushButton(self.widget)
        self.g4.setStyleSheet("background-color:rgb(0,0,0)\n"
"\n"
"\n"
"")
        self.g4.setText("")
        self.g4.setObjectName("g4")
        self.verticalLayout_4.addWidget(self.g4)
        self.g5 = QtWidgets.QPushButton(self.widget)
        self.g5.setStyleSheet("background-color:rgb(0,0,0)\n"
"\n"
"")
        self.g5.setText("")
        self.g5.setObjectName("g5")
        self.verticalLayout_4.addWidget(self.g5)
        self.g6 = QtWidgets.QPushButton(self.widget)
        self.g6.setStyleSheet("background-color:rgb(0,0,0)\n"
"\n"
"")
        self.g6.setText("")
        self.g6.setObjectName("g6")
        self.verticalLayout_4.addWidget(self.g6)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 5)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.widget, "")
        self.Piano = QtWidgets.QWidget()
        self.Piano.setObjectName("Piano")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Piano)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.Piano)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.p1 = QtWidgets.QPushButton(self.Piano)
        self.p1.setMinimumSize(QtCore.QSize(0, 70))
        self.p1.setMaximumSize(QtCore.QSize(50, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 6, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 12, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 6, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 12, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 6, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 12, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        self.p1.setPalette(palette)
        self.p1.setStyleSheet("background-color:rgb(255, 0, 123)")
        self.p1.setText("")
        self.p1.setObjectName("p1")
        self.horizontalLayout.addWidget(self.p1)
        self.p2 = QtWidgets.QPushButton(self.Piano)
        self.p2.setMinimumSize(QtCore.QSize(0, 70))
        self.p2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p2.setStyleSheet("background-color:rgb(163, 15, 255)\n"
"")
        self.p2.setText("")
        self.p2.setObjectName("p2")
        self.horizontalLayout.addWidget(self.p2)
        self.p3 = QtWidgets.QPushButton(self.Piano)
        self.p3.setMinimumSize(QtCore.QSize(0, 70))
        self.p3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p3.setStyleSheet("background-color:\n"
"rgb(107, 94, 255)")
        self.p3.setText("")
        self.p3.setObjectName("p3")
        self.horizontalLayout.addWidget(self.p3)
        self.p4 = QtWidgets.QPushButton(self.Piano)
        self.p4.setMinimumSize(QtCore.QSize(0, 70))
        self.p4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p4.setStyleSheet("background-color:rgb(0, 255, 170)")
        self.p4.setText("")
        self.p4.setObjectName("p4")
        self.horizontalLayout.addWidget(self.p4)
        self.p5 = QtWidgets.QPushButton(self.Piano)
        self.p5.setMinimumSize(QtCore.QSize(0, 70))
        self.p5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p5.setStyleSheet("background-color:rgb(0, 170, 127)")
        self.p5.setText("")
        self.p5.setObjectName("p5")
        self.horizontalLayout.addWidget(self.p5)
        self.p6 = QtWidgets.QPushButton(self.Piano)
        self.p6.setMinimumSize(QtCore.QSize(0, 70))
        self.p6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p6.setStyleSheet("background-color:rgb(255, 76, 76)")
        self.p6.setText("")
        self.p6.setObjectName("p6")
        self.horizontalLayout.addWidget(self.p6)
        self.p7 = QtWidgets.QPushButton(self.Piano)
        self.p7.setMinimumSize(QtCore.QSize(0, 70))
        self.p7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p7.setStyleSheet("background-color:\n"
"rgb(255, 56, 82)")
        self.p7.setText("")
        self.p7.setObjectName("p7")
        self.horizontalLayout.addWidget(self.p7)
        self.p8 = QtWidgets.QPushButton(self.Piano)
        self.p8.setMinimumSize(QtCore.QSize(0, 70))
        self.p8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.p8.setStyleSheet("background-color:rgb(153, 153, 153)")
        self.p8.setText("")
        self.p8.setObjectName("p8")
        self.horizontalLayout.addWidget(self.p8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.p9 = QtWidgets.QPushButton(self.Piano)
        self.p9.setMinimumSize(QtCore.QSize(0, 270))
        self.p9.setStyleSheet("background-color:rgb(251, 197, 255)")
        self.p9.setText("")
        self.p9.setObjectName("p9")
        self.horizontalLayout_2.addWidget(self.p9)
        self.p10 = QtWidgets.QPushButton(self.Piano)
        self.p10.setMinimumSize(QtCore.QSize(0, 270))
        self.p10.setStyleSheet("background-color:rgb(255, 167, 169)")
        self.p10.setText("")
        self.p10.setObjectName("p10")
        self.horizontalLayout_2.addWidget(self.p10)
        self.p11 = QtWidgets.QPushButton(self.Piano)
        self.p11.setMinimumSize(QtCore.QSize(0, 270))
        self.p11.setStyleSheet("background-color:\n"
"\n"
"rgb(198, 133, 255)")
        self.p11.setText("")
        self.p11.setObjectName("p11")
        self.horizontalLayout_2.addWidget(self.p11)
        self.p12 = QtWidgets.QPushButton(self.Piano)
        self.p12.setMinimumSize(QtCore.QSize(0, 270))
        self.p12.setStyleSheet("background-color:rgb(192, 183, 255)\n"
"")
        self.p12.setText("")
        self.p12.setObjectName("p12")
        self.horizontalLayout_2.addWidget(self.p12)
        self.p13 = QtWidgets.QPushButton(self.Piano)
        self.p13.setMinimumSize(QtCore.QSize(0, 270))
        self.p13.setStyleSheet("background-color:rgb(180, 198, 255)")
        self.p13.setText("")
        self.p13.setObjectName("p13")
        self.horizontalLayout_2.addWidget(self.p13)
        self.p14 = QtWidgets.QPushButton(self.Piano)
        self.p14.setMinimumSize(QtCore.QSize(0, 270))
        self.p14.setStyleSheet("background-color:rgb(207, 255, 209)")
        self.p14.setText("")
        self.p14.setObjectName("p14")
        self.horizontalLayout_2.addWidget(self.p14)
        self.p15 = QtWidgets.QPushButton(self.Piano)
        self.p15.setMinimumSize(QtCore.QSize(0, 270))
        self.p15.setStyleSheet("background-color:rgb(203, 255, 178)")
        self.p15.setText("")
        self.p15.setObjectName("p15")
        self.horizontalLayout_2.addWidget(self.p15)
        self.p16 = QtWidgets.QPushButton(self.Piano)
        self.p16.setMinimumSize(QtCore.QSize(0, 270))
        self.p16.setStyleSheet("background-color:\n"
"rgb(255, 219, 174)")
        self.p16.setText("")
        self.p16.setObjectName("p16")
        self.horizontalLayout_2.addWidget(self.p16)
        self.p17 = QtWidgets.QPushButton(self.Piano)
        self.p17.setMinimumSize(QtCore.QSize(0, 270))
        self.p17.setStyleSheet("background-color:\n"
"rgb(255, 209, 178)")
        self.p17.setText("")
        self.p17.setObjectName("p17")
        self.horizontalLayout_2.addWidget(self.p17)
        self.p18 = QtWidgets.QPushButton(self.Piano)
        self.p18.setMinimumSize(QtCore.QSize(0, 270))
        self.p18.setText("")
        self.p18.setObjectName("p18")
        self.horizontalLayout_2.addWidget(self.p18)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Piano, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MusicalInstruments.setCentralWidget(self.centralwidget)
        self.Open = QtWidgets.QAction(MusicalInstruments)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../task1-team__12/project/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Open.setIcon(icon1)
        self.Open.setObjectName("Open")
        self.Save = QtWidgets.QAction(MusicalInstruments)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../task1-team__12/project/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save.setIcon(icon2)
        self.Save.setObjectName("Save")
        self.UndoRecord = QtWidgets.QAction(MusicalInstruments)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../task1-team__12/project/zoom in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UndoRecord.setIcon(icon3)
        self.UndoRecord.setObjectName("UndoRecord")
        self.Cut = QtWidgets.QAction(MusicalInstruments)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/Cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cut.setIcon(icon4)
        self.Cut.setObjectName("Cut")
        self.TCopy = QtWidgets.QAction(MusicalInstruments)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TCopy.setIcon(icon5)
        self.TCopy.setObjectName("TCopy")
        self.TPaste = QtWidgets.QAction(MusicalInstruments)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TPaste.setIcon(icon6)
        self.TPaste.setObjectName("TPaste")
        self.About_us = QtWidgets.QAction(MusicalInstruments)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../task1-team__12/project/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.About_us.setIcon(icon7)
        self.About_us.setObjectName("About_us")
        self.Refresh = QtWidgets.QAction(MusicalInstruments)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../task1-team__12/project/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Refresh.setIcon(icon8)
        self.Refresh.setObjectName("Refresh")
        self.Paste = QtWidgets.QAction(MusicalInstruments)
        self.Paste.setIcon(icon6)
        self.Paste.setObjectName("Paste")
        self.Copy = QtWidgets.QAction(MusicalInstruments)
        self.Copy.setIcon(icon5)
        self.Copy.setObjectName("Copy")
        self.Duplicate = QtWidgets.QAction(MusicalInstruments)
        self.Duplicate.setObjectName("Duplicate")
        self.Zoom_In = QtWidgets.QAction(MusicalInstruments)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/zoom in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Zoom_In.setIcon(icon9)
        self.Zoom_In.setObjectName("Zoom_In")
        self.Zoom_Out = QtWidgets.QAction(MusicalInstruments)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/zoom out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Zoom_Out.setIcon(icon10)
        self.Zoom_Out.setObjectName("Zoom_Out")
        self.Pause = QtWidgets.QAction(MusicalInstruments)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Pause.setIcon(icon11)
        self.Pause.setObjectName("Pause")
        self.Play = QtWidgets.QAction(MusicalInstruments)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play.setIcon(icon12)
        self.Play.setObjectName("Play")
        self.Stop = QtWidgets.QAction(MusicalInstruments)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stop.setIcon(icon13)
        self.Stop.setObjectName("Stop")
        self.Previous = QtWidgets.QAction(MusicalInstruments)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Previous.setIcon(icon14)
        self.Previous.setObjectName("Previous")
        self.Next = QtWidgets.QAction(MusicalInstruments)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/end.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Next.setIcon(icon15)
        self.Next.setObjectName("Next")
        self.Record = QtWidgets.QAction(MusicalInstruments)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Record.setIcon(icon16)
        self.Record.setObjectName("Record")
        self.Microphone = QtWidgets.QAction(MusicalInstruments)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/microphone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Microphone.setIcon(icon17)
        self.Microphone.setObjectName("Microphone")
        self.Volume_on = QtWidgets.QAction(MusicalInstruments)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/volume on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Volume_on.setIcon(icon18)
        self.Volume_on.setObjectName("Volume_on")
        self.Redo = QtWidgets.QAction(MusicalInstruments)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Redo.setIcon(icon19)
        self.Redo.setObjectName("Redo")
        self.Undo = QtWidgets.QAction(MusicalInstruments)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("../../Lenovo Legion/.designer/backup/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Undo.setIcon(icon20)
        self.Undo.setObjectName("Undo")

        self.retranslateUi(MusicalInstruments)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MusicalInstruments)

    def retranslateUi(self, MusicalInstruments):
        _translate = QtCore.QCoreApplication.translate
        MusicalInstruments.setWindowTitle(_translate("MusicalInstruments", "MusicalInstruments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MusicalInstruments", "Tab 1"))
        self.label.setText(_translate("MusicalInstruments", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#550000;\">Piano</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Piano), _translate("MusicalInstruments", "Tab 2"))
        self.Open.setText(_translate("MusicalInstruments", "Open"))
        self.Open.setStatusTip(_translate("MusicalInstruments", "Open a file"))
        self.Open.setShortcut(_translate("MusicalInstruments", "Ctrl+O"))
        self.Save.setText(_translate("MusicalInstruments", "Save"))
        self.Save.setStatusTip(_translate("MusicalInstruments", "Save the file"))
        self.Save.setShortcut(_translate("MusicalInstruments", "Ctrl+S"))
        self.UndoRecord.setText(_translate("MusicalInstruments", "Undo Record"))
        self.UndoRecord.setStatusTip(_translate("MusicalInstruments", "Maximize"))
        self.UndoRecord.setShortcut(_translate("MusicalInstruments", "Ctrl++"))
        self.Cut.setText(_translate("MusicalInstruments", "Cut"))
        self.Cut.setStatusTip(_translate("MusicalInstruments", "Minimize"))
        self.Cut.setShortcut(_translate("MusicalInstruments", "Ctrl+-"))
        self.TCopy.setText(_translate("MusicalInstruments", "Copy"))
        self.TCopy.setShortcut(_translate("MusicalInstruments", "Ctrl+C"))
        self.TPaste.setText(_translate("MusicalInstruments", "Paste"))
        self.TPaste.setShortcut(_translate("MusicalInstruments", "Ctrl+V"))
        self.About_us.setText(_translate("MusicalInstruments", "About us"))
        self.About_us.setShortcut(_translate("MusicalInstruments", "Ctrl+F"))
        self.Refresh.setText(_translate("MusicalInstruments", "Refresh"))
        self.Refresh.setStatusTip(_translate("MusicalInstruments", "Refresh"))
        self.Paste.setText(_translate("MusicalInstruments", "Paste"))
        self.Copy.setText(_translate("MusicalInstruments", "Copy"))
        self.Duplicate.setText(_translate("MusicalInstruments", "Duplicate"))
        self.Zoom_In.setText(_translate("MusicalInstruments", "Zoom In"))
        self.Zoom_Out.setText(_translate("MusicalInstruments", "Zoom Out"))
        self.Pause.setText(_translate("MusicalInstruments", "Pause"))
        self.Play.setText(_translate("MusicalInstruments", "Play"))
        self.Stop.setText(_translate("MusicalInstruments", "Stop"))
        self.Previous.setText(_translate("MusicalInstruments", "Previous"))
        self.Next.setText(_translate("MusicalInstruments", "Next"))
        self.Record.setText(_translate("MusicalInstruments", "Record"))
        self.Microphone.setText(_translate("MusicalInstruments", "Microphone"))
        self.Volume_on.setText(_translate("MusicalInstruments", "Volume on"))
        self.Redo.setText(_translate("MusicalInstruments", "Redo"))
        self.Undo.setText(_translate("MusicalInstruments", "Undo"))

	

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MusicalInstruments = QtWidgets.QMainWindow()
    ui = Ui_MusicalInstruments()
    ui.setupUi(MusicalInstruments)
    MusicalInstruments.show()
    sys.exit(app.exec_())

